### ISSUE TITLE
OS X: video render fails

### ISSUE THREAD

**Issue by seppviljar** [Iniquitatis/sd-webui-temporal#1]
[fd @ 0x600003bfc000] Doesn't support pass file descriptor via URL, please set it via -fd {num}
[concat @ 0x153804290] Impossible to open 'fd:/Users/sepp/Stable/stable-diffusion-webui/outputs/temporal/untitled/00001.png'
fd:: Invalid argument

**Comment by Iniquitatis** [comment]
@seppviljar Could you please update the extension and try again to confirm whether it's fixed or not? I don't have an OSX machine, so can't test it myself.

**Comment by seppviljar** [comment]
Seems to work, thanks
